import { createRoot } from "react-dom/client";
import { App } from "./CardCollection";
import styled from "styled-components";

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

export default function Root() {
  return (
      <Wrapper>
        <App />
        {/* <div
          style={{
            position: "absolute",
            pointerEvents: "none",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
          }}
        >
          <a
            href="https://pmnd.rs/"
            style={{
              position: "absolute",
              bottom: 40,
              left: 90,
              fontSize: "13px",
            }}
          >
            pmnd.rs
            <br />
            dev collective
          </a>
          <div
            style={{
              position: "absolute",
              bottom: 40,
              right: 40,
              fontSize: "13px",
            }}
          >
            18/01/2024
          </div>
          <a
            style={{
              position: "absolute",
              top: 40,
              left: 40,
              fontSize: "13px",
            }}
            href="#"
          >
            scroll up/down ...
          </a>
        </div>{" "} */}
      </Wrapper>
  );
}

const Wrapper = styled.div`
  @import url("https://rsms.me/inter/inter.css");

    box-sizing: border-box;

  width: 100%;
  height: 100vh;
  margin: 0;
  padding: 0;

  font-family: "Inter";
  background: #fdfdfd;
  cursor: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48Y2lyY2xlIGN4PSIxNiIgY3k9IjE2IiByPSIxMCIgZmlsbD0iI0U4QjA1OSIvPjwvc3ZnPg=="),
    auto;

  a {
    color: black;
  }

  a {
    pointer-events: all;
    color: black;
    text-decoration: none;
  }

  svg {
    fill: black;
  }

  @keyframes fade-in {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  canvas {
    opacity: 0;
    touch-action: none;
    animation: fade-in 5s ease 1s forwards;
  }
`;
